### ISSUE TITLE
Sentry client truncates "culprit" field in JSON

### ISSUE THREAD

**Issue by samphilipd** [getsentry/sentry-elixir#210]
Here is an example "culprit" send from our app:

`"CloseIO.HTTPClient.handle_response({:ok, %HTTPoison.Response{body: %{\"field-errors\" => %{\"phones\" => %{\"0\" => %{\"phone\" => \"Phone number is not valid. Please use the international format like +1650..."`

As a developer I would like to see the full, untruncated culprit message in the JSON to allow for easier debugging in case logs are not available, and to make it easier to find the error in the logs if they are available.

**Comment by mitchellhenke** [comment]
This is a limitation on the server side of Sentry here, which will limit culprit to 200 characters: https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py#L72

Technically, the culprit is supposed to be just a function call (absent any args) ([link to sentry doc](https://docs.sentry.io/clientdev/attributes/#optional-attributes)), but as Elixir is different in that the args also play a role in that in a way, we've always included them.

I'll explore how we can include them without being truncated, potentially under a different key, and see if something more helpful can be added server-side as well.
