### ISSUE TITLE
Usage of Event Stacktrace is deprecated but still used here 

### ISSUE THREAD

**Issue by bufke** [getsentry/sentry-elixir#487]
### Environment

sentry-elixir 8.0.5 as demonstrated in https://gitlab.com/glitchtip/error-factories/elixir-error-factory

### Steps to Reproduce

1. Run example repo and inspect event data produced by this SDK.

### Expected Result

stacktrace should show up in exception

### Actual Result

stacktrace shows up in stacktrace field instead. Which is marked as deprecated for some time in https://develop.sentry.dev/sdk/event-payloads/types/

Abbreviated example of event data

```
{
...
"stacktrace": {
    "frames": [
      {
        "context_line": null,
        "filename": "proc_lib.erl",
        "function": ":proc_lib.init_p_do_apply/3",
        "in_app": false,
        "lineno": 226,
        "module": "proc_lib",
        "post_context": [],
        "pre_context": [],
        "vars": {}
      },
      ...
}
```

**Comment by whatyouhide** [comment]
Yes, we can use the new API. However, since `Sentry.Event` is public, I suggest we change it to match the public API, **hide it from the docs**, and make this change part of the 9.0.0 release (since it's a breaking change). Hiding it will let us be more flexible in the future with changes, and I don't think user necessarily need it exposed.

@sl0thentr0py, what do you think?

**Comment by sl0thentr0py** [comment]
@whatyouhide yes sounds good to me
