### ISSUE TITLE
Question: why stacktrace args limit is 513?

### ISSUE THREAD

**Issue by samuelpordeus** [getsentry/sentry-elixir#499]
Sorry if this is not the place to ask questions, but here it is:

Some of our error args were being truncated at `513` characters, I found this code related to it here:
```elixir
  @spec args_from_stacktrace(Exception.stacktrace()) :: map()
  def args_from_stacktrace([{_m, _f, a, _} | _]) when is_list(a) do
    Enum.with_index(a)
    |> Enum.into(%{}, fn {arg, index} ->
      {"arg#{index}", String.slice(inspect(arg, limit: 513, printable_limit: 513), 0, 513)}
    end)
  end
```
https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/event.ex#L278-L283

Is there any reasoning on why `513`? it looks like it can be something related to performance, but I couldn't find any mention of it here. If there's interest I could open a PR to be able to tweak it.

Thanks! ❤️

**Comment by mitchellhenke** [comment]
This is a perfectly okay place to ask, no apology necessary 🙂

The size constraint is due to API limits around the size of an event on Sentry server-side (or was at the time of https://github.com/getsentry/sentry-elixir/issues/332). If the limit is higher now, I'd be glad to raise it here, but if not, I'd be wary of causing failures from sending events that are too large and end up being rejected by the server.

**Comment by kinson** [comment]
Thanks for the reply @mitchellhenke - event size limits make sense! 

It looks like the [max size of events is now 200kb](https://develop.sentry.dev/sdk/event-payloads/). I am not sure if this has changed since #332 though.

Out of curiosity, how do you measure event size? Is there a tool/package you use while developing or is it from inspecting some attribute of the event on Sentry itself?

**Comment by mitchellhenke** [comment]
I think that’s the tricky part, since the ultimate event size isn’t known until it’s put together. The Sentry site shows the size of the events as JSON, and that’s been kind of my guide.

**Comment by mitchellhenke** [comment]
Closing this for now 🙂

**Comment by prem-prakash** [comment]
What about trimming the payload after it is built?

**Comment by PJUllrich** [comment]
@solnic do you think Sentry could revisit this limitation maybe? This is an issue with very large Elixir structs unfortunately. It's okay for now because I can ask my coworker to dive into the prod DB to check the records, but it'd be nicer to have that data inside the Sentry event.

**Comment by solnic** [comment]
@PJUllrich yes we can revisit this. The limit is now 1MB for event items so it's bigger. I'm also not sure if we actually want to continue dumping structs there. Maybe it would be better to have a dedicated simple representation for structs with just its type and then dump its state as extra info in the context. I'll see what other SDKs are doing in similar cases.
