### ISSUE TITLE
Duplicate "an exception was raised" error when using LoggerBackend

### ISSUE THREAD

**Issue by TheFirstAvenger** [getsentry/sentry-elixir#535]
We have `{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)` in our `Application.start`, and recently added `config :logger, Sentry.LoggerBackend, capture_log_messages: true` in our `config.exs`. We added this so we can capture manual `Logger.error` calls we have in our code. When we added `capture_lot_messages: true`, in addition to it correctly capturing manual `Logger.error` calls, we started getting a second error every time a regular error was captured in Sentry.

For example, a `FunctionClauseError` recently happened, and there is an issue in Sentry with `FunctionClauseError` as its title (which is expected), but there is also an issue with `an exception was raised:` as its title and the stack trace in the message (this is not expected). Every exception that has been captured since adding `capture_log_messages: true` has this second error.

The confusing thing is that I currently have this exact config on two different projects, and it is happening on one but not the other. I am not able to find any difference between the two projects from a Sentry config standpoint, both are Sentry `8.0.6` and both are on the same version of Elixir & Erlang (1.14.2/25.1.2). It looks like the duplicates happen when errors trigger in LiveViews, but not for background exceptions.

**Comment by aselder** [comment]
We're seeing this as well.

**Comment by whatyouhide** [comment]
@TheFirstAvenger @aselder are you folks still seeing this in 9.0.0? 🙃

**Comment by whatyouhide** [comment]
Hi @aselder, any news? I want to push out a new Sentry release, and I’m just trying to figure out if we'll have a chance to address this issue in that release 😉

**Comment by aselder** [comment]
@whatyouhide Actually working on the upgrade as we speak. Depending on what things come up to distract me, I hope to have it done tomorrow.

**Comment by whatyouhide** [comment]
Ping @aselder 🙃

**Comment by whatyouhide** [comment]
There were significant changes around all this, so I'm going to close this for now assuming that this is not currently happening. If it is, folks are welcome to comment down here and we'll reopen the issue 🙃

**Comment by aej** [comment]
Ive been seeing this issue too with similar patterns:

* Happens in LiveView
* There is one exception which is correctly sent to Sentry with a stacktrace
* A duplicate is sent to sentry with the message `an exception was raised:...` which has no stacktrace and is just a dump of stacktrace in he message
* v10.0.2

Interestingly the duplicate has the following Logger metadata:

```
{
    application: phoenix, 
    domain: [
        elixir
    ], 
    file: lib/phoenix/channel/server.ex, 
    gl: #PID<0.4945.0>, 
    line: 41, 
    mfa: {Phoenix.Channel.Server, :join, 4}, 
    pid: #PID<0.2496968.0>, 
    time: 1701386021067851
}
```

Having a look at this line in Phoenix- source: https://github.com/phoenixframework/phoenix/blob/v1.6/lib/phoenix/channel/server.ex#L41C66-L41C66

```elixir
...
{:DOWN, ^mon_ref, _, _, reason} ->
  Logger.error(fn -> Exception.format_exit(reason) end)
  {:error, %{reason: "join crashed"}}
```

So Im guessing Phoenix is catching the crash of the liveview, converting the exception to a string and we are sending it to sentry again without the stacktrace.

So unless Im mistaken, the bug is actually on the phoenix-side
