### ISSUE TITLE
Can source code context work on module name instead of file to improve umbrella apps compatibility?

### ISSUE THREAD

**Issue by hkrutzer** [getsentry/sentry-elixir#638]
I have `enable_source_code_context` disabled because I have duplicate file names across umbrella apps and Sentry tries to match the stacktrace with a file. But if I open a JSON payload for an event in Sentry, it shows `"function": $UMBRELLA_APP.ModuleName.Etc`. So the client is aware of which module this error is coming from. Isn't it possible to map the stacktrace to source code using this information, instead of mapping to a file which in umbrella apps you have to guess which one it is?

**Comment by whatyouhide** [comment]
The problem is mapping the modules to their location. We don't want to be clever here and try to figure out where modules are defined, so we fetch by file name in the stacktrace to show the context. One thing we could do, however, is probably make the the **application** part of the key to fetch context. This way, you could have `apps/app1/lib/my_mod.ex` and `apps/app2/lib/my_mod.ex` (same relative path), but if `:app1` and `:app2` are part of the key then we should be fine. I need to investigate this a bit more.

**Comment by whatyouhide** [comment]
Okay, I investigated this. We cannot do something like what I proposed with the application name and all. For now, raising on conflicting paths is the best approach IMO. This is usually something users can fix by renaming files in the worst case. I will try to issue a nicer error message when conflicts happen. Thank you!

**Comment by hkrutzer** [comment]
Thanks for looking into this! What do you think of the way `Plug.Debugger` finds source code when displaying an error in local development?
