### ISSUE TITLE
Message interpolation

### ISSUE THREAD

**Issue by whatyouhide** [getsentry/sentry-elixir#664]
Messages support interpolation:

```json
{
  "message": {
    "message": "My raw message with interpreted strings like %s",
    "params": ["this"]
  }
}
```

I assume this is used to easily group messages regardless of the values being interpolated. If so, I think we should support this in the `Sentry.capture_message/1` function. A couple of proposed APIs:

```elixir
# Option #1: with a tuple
Sentry.capture_message({"Interpolated %s", ["message"]}, options)

# Option #2: through options
Sentry.capture_message("Interpolated %s", formatting_parameters: ["message"])
```

**Comment by whatyouhide** [comment]
cc @sl0thentr0py

**Comment by sl0thentr0py** [comment]
yes indeed, we do [this in python](https://github.com/getsentry/sentry-python/blob/fe079c8c5a9f913f4051599b94739e859bee1339/sentry_sdk/integrations/logging.py#L242-L245) in our logging integration but we don't expose the params in `capture_message` yet, but we should.

I like option 2 a bit more, because it makes the optionality explicit.
