### ISSUE TITLE
Clarify `:included_environments` deprecated option

### ISSUE THREAD

**Issue by sescobb27** [getsentry/sentry-elixir#695]
### Environment

Sentry 10.1.0

### Steps to Reproduce

we migrated from sentry 8 to version 10.1.0, and we are getting the following error regarding the use of `:included_environments`

```elixir
warning: :included_environments option is deprecated. Use :dsn to control whether to send events to Sentry.
  (nimble_options 1.1.0) lib/nimble_options.ex:572: NimbleOptions.validate_value/3
  (nimble_options 1.1.0) lib/nimble_options.ex:558: NimbleOptions.validate_option/3
  (nimble_options 1.1.0) lib/nimble_options.ex:540: NimbleOptions.reduce_options/2
  (elixir 1.16.1) lib/enum.ex:4842: Enumerable.List.reduce/3
  (elixir 1.16.1) lib/enum.ex:2582: Enum.reduce_while/3
  (nimble_options 1.1.0) lib/nimble_options.ex:533: NimbleOptions.validate_options/2
```

the thing is you are still checking for it here https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry.ex#L333 and not using `Config.dsn` as you said in the error message, so maybe if dsn is present have the same logic as with included environments? so we can get rid of `included_environments` config and warning

### Expected Result

to not have a warning

### Actual Result

a warning

**Comment by whatyouhide** [comment]
Hi @sescobb27, thanks for the report!

Here's [the code you linked to](https://github.com/getsentry/sentry-elixir/blob/1ac4b93052fa955438ea575ce87cbceeaa80f217/lib/sentry.ex#L330-L334):

```elixir
      !Config.dsn() ->
        :ignored

      included_envs == :all or to_string(Config.environment_name()) in included_envs ->
        Client.send_event(event, opts)
```

As you can see, we *do* check for `:dsn` and, if not set, we ignore the event. If it's set, we still check for `:included_environments`, but that's because the option is **deprecated**, not **removed**. We need to deprecated it for a couple of version but still allow it to work, to give folks time to upgrade versions without breaking.

Does that make sense? Am I missing something?

**Comment by sescobb27** [comment]
hi @whatyouhide, sure. warning message says: `warning: :included_environments option is deprecated. Use :dsn to control whether to send events to Sentry.` so, if we use `:dsn` alone without `:included_environments` should work, but because it is being `:ignored` we still need to use `:included_environments` i was imagining the fix would be something like

```elixir
      !Config.dsn() ->
        # don't ignore it but instead use it as the warning says
        Client.send_event(event, opts)

      included_envs == :all or to_string(Config.environment_name()) in included_envs ->
        Client.send_event(event, opts)
```

**Comment by whatyouhide** [comment]
@sescobb27 that would be a breaking change. Imagine someone has `:dsn` set (which is most people), and they also use `:included_environments`. While we want to _deprecate_ `:included_environments`, if we always send the event just if `:dsn` is set then we would effectively **stop using `:included_environments`**, which is a breaking change.

In fact, for now we default `:included_environments` to `:all` if you don't pass it, so that the lines

```elixir
included_envs == :all or to_string(Config.environment_name()) in included_envs ->
  Client.send_event(event, opts)
```

always pass through if you don't set `:included_environments`. So, if you just remove `:included_environments` from your configuration and just use `:dsn` you will be able to control when to send events and you will be able to get rid of the warning.

**Comment by sescobb27** [comment]
oh ok i see, thank you very much, i'm closing this then
