### ISSUE TITLE
Unable to test before_send in development

### ISSUE THREAD

**Issue by hunterboerner** [getsentry/sentry-elixir#735]
When I'm running this package in development I do not get any calls to my custom `before_send` handler. This project is available here: https://github.com/stereowrench/visual_garden

Am I doing something wrong or is this expected behavior? Do I need a DSN set for the `before_send` callback to be called?

**Comment by whatyouhide** [comment]
Interesting, but yeah I think that's expected. [Sentry SDK guidelines](https://develop.sentry.dev/sdk/unified-api/#event-pipeline) explicitly say that the event should be thrown away if the SDK is disabled—which it is if DSN is not configured.

We already have `test_mode` so we might switch to going through `before_send` hooks in test mode, maybe that makes sense.

**Comment by savhappy** [comment]
@hunterboerner this is the expected behavior and by design the DSN is set to nil if not given and no events are sent. See table in [test.ex](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/test.ex). You can collect events in `test_mode` and test your custom hook functions via `start_collecting`

You'll need to set your DSN if you want to test in dev.

**Comment by whatyouhide** [comment]
@hunterboerner yes to add to what @savhappy said, if you set DSN to `nil` then it's expected that no events get reported. If you set it to a non-`nil` value and you have `test_mode: true`, you will still have to call `Sentry.Test.start_collecting_sentry_reports/1` in your tests if you want to collect events. If you do that, those events should go through `before_send` as well. If they don't, feel free to comment down here and we'll figure it out.

Btw, the docs for `Sentry.Test` have a bunch more information on this, hopefully that's helpful!
