### ISSUE TITLE
JSON payload not showing in dashboard

### ISSUE THREAD

**Issue by Mazyod** [getsentry/sentry-elixir#86]
So, I was testing my first exception using HTTPie. Even though the request clearly has a body which is raising an exception, and that exception is properly reported in Sentry, the report doesn't include the body of the request. Instead, it just shows the body as `{}`.

For extra details, I using v1.1.1, Elixir v1.3.3, OTP 19, Phoenix 1.2.1.

```bash
POST [path] HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 23
Content-Type: application/json
Host: [host]
User-Agent: HTTPie/0.9.6

{
    "account_uid": "blah"
}

HTTP/1.1 400 Bad Request
cache-control: max-age=0, private, must-revalidate
content-length: 45
content-type: application/json; charset=utf-8
date: Tue, 15 Nov 2016 14:49:01 GMT
server: Cowboy

{
    "errors": {
        "detail": "Internal server error"
    }
}
```

<img width="1000" alt="screen_shot_2016-11-15_at_4_01_44_pm" src="https://cloud.githubusercontent.com/assets/860511/20310630/fd0feab4-ab4c-11e6-8d61-7c29d05eb1db.png">

**Comment by mitchellhenke** [comment]
This is due to not providing a function to scrub sensitive data (relevant docs are [here](https://hexdocs.pm/sentry/1.1.1/Sentry.Plug.html)).  By default, the library doesn't attempt to scrub things like password, credit card, etc. and depends on the user to provide a function to do so.  This was done initially to avoid unintentionally sending sensitive information without the user specifying what should be excluded.  For reference, the implementation is [here](https://github.com/getsentry/sentry-elixir/blob/6c2b2da4025f781b09239d91e9824015819c8b26/lib/sentry/plug.ex#L99-L105).

That said, other Sentry libraries do include default scrubbers, so I'll add one here as well.  Thanks for creating this issue 🙂
